name: reactomic_design
description: "A new Flutter package project."
version: 0.0.1
homepage: https://example.com

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter_gen:
  output: lib/tokens/gen

  integrations:
    flutter_svg: true
    lottie: true

  assets:
    enabled: true
    outputs:
      class_name: AssetsToken
      package_parameter_enabled: true
      # Assets.imagesChip
      # style: camel-case
      # Assets.images_chip
      # style: snake-case
      # Assets.images.chip (default style)
      style: dot-delimiter
    # exclude:
    #   - assets-extern/*
    #   - pictures/chip5.jpg
  fonts:
    enabled: true
    outputs:
      class_name: FontsToken

  colors:
    enabled: true
    outputs:
      class_name: ColorsToken
    inputs:
      - assets/colors/colors.xml
flutter:
  uses-material-design: true
  assets:
    - assets/colors/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-Italic.ttf
          style: italic
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
